version: "3"
services:
  db:
    image: postgres:latest
    container_name: reddit-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DBDB_USER_ID}"
      POSTGRES_PASSWORD: "{DB_USER_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
